routes/web.php
    Route::match(['DELETE', 'PUT', 'GET', 'POST'], 'eshantion/{id?}', 'AdminController@eshantion')->name('eshantion');
    Route::get('visitorlog', 'AdminController@visitorlog')->name('visitorlog');

    //Route::get('profile/show/', 'IndexController@profile')->name('user.profile');//unused

    //Route::post('/profile/payFactor', 'IndexController@payFactor')->name('pay.factor');//unused

    //Route::get('/pmBox', 'IndexController@pmBox')->name('pmBox.get');//unused

    Route::post('/discountPost', 'IndexController@discountPost')->name('discount.post');

    Route::any('discountFestival', 'DiscountForAllController@discountFestival')->name('discountFestival');

    Route::any('discountForProducts', 'DiscountForAllController@discountForProducts')->name('discountForProducts');
    Route::any('discountForCategoryOfProducts', 'DiscountForAllController@discountForCategoryOfProducts')->name('discountForCategoryOfProducts');
    Route::any('discountForUsers', 'DiscountForAllController@discountForUsers')->name('discountForUsers');

    Route::any('discountCodeForProducts', 'DiscountForAllController@discountCodeForProducts')->name('discountCodeForProducts');
    Route::any('discountCodeForCategoryOfProducts', 'DiscountForAllController@discountCodeForCategoryOfProducts')->name('discountCodeForCategoryOfProducts');
    Route::any('discountCodeForUsers', 'DiscountForAllController@discountCodeForUsers')->name('discountCodeForUsers');

    Route::any('discountForPrice', 'DiscountForAllController@discountForPrice')->name('discountForPrice');

    //Route::get('/userFactors', 'ProfileController@userFactors')->name('userFactors');//unused
    //Route::get('/profile', 'ProfileController@profileGet')->name('profile.get');//unused
    Route::get('/profile/edit', 'ProfileController@profileEdit')->name('profile.edit');
    Route::post('/profile/post', 'ProfileController@profilePost')->name('profile.post');
    Route::post('profile/financialIncreaseBalance', 'ProfileController@increaseBalancePost')->name('increase.balance.post');
    Route::get('profile/financialIncreaseBalance', 'ProfileController@increaseBalanceGet')->name('increase.balance.get');
    Route::get('profile/financialDepartment', 'ProfileController@financialDepartment')->name('financialDepartment');
    Route::match(['GET', 'POST'], 'profile/financialWithdraw', 'ProfileController@financialWithdraw')->name('financialWithdraw');

    Route::match(['GET', 'POST'], 'profile/ticketCreate', 'ProfileController@ticketCreate')->name('ticketCreate');
    Route::match(['GET', 'POST'], 'profile/ticketComments/{id}', 'ProfileController@ticketComments')->name('ticketComments');
    Route::get('profile/ticketIndex', 'ProfileController@ticketIndex')->name('ticketIndex');//unused
    Route::get('profile/userCourses', 'ProfileController@userCourses')->name('userCourses');
    Route::get('profile/courseStudent', 'ProfileController@courseStudent')->name('courseStudent');

    Route::get('profile/teachingIndex', 'ProfileController@teachingIndex')->name('teachingIndex');
    Route::match(['GET', 'POST'], 'profile/teachingRequestCreate', 'ProfileController@teachingRequestCreate')->name('teachingRequestCreate');
    Route::match(['GET', 'POST'], 'profile/teachingRequestComments/{id}', 'ProfileController@teachingRequestComments')->name('teachingRequestComments');
    Route::get('profile/teacherEditProducts/{product}', 'ProductController@teacherEditProducts')->name('teacherEditProducts');
    Route::post('profile/teacherUpdateProducts/{product}', 'ProductController@teacherUpdateProducts')->name('teacherUpdateProducts');

    Route::get('post/{post}', 'IndexController@showAPost')->name('show.post');
    //Route::get('productPost/{productPost}', 'IndexController@showProductPost')->name('show.product.post');//unused

    Route::match(['GET', 'POST'], 'adminFinancialWithdraw/{balanceHistory?}', 'AdminController@adminFinancialWithdraw')->name('adminFinancialWithdraw');
    Route::get('upload', 'UploadController@uploadGet')->name('upload.get');
    Route::post('upload', 'UploadController@uploadPost')->name('upload.post');

    Route::post('addToBasket/{id}', 'IndexController@addToBasket')->name('add.to.basket');
    Route::post('removeFromBasket/{id}', 'IndexController@removeFromBasket')->name('remove.from.basket');
    Route::put('signUpNoPrice/{id}', 'IndexController@signUpNoPrice')->name('signUpNoPrice');

    Route::get('checkOut', 'IndexController@checkOut')->name('check.out');

    Route::get('shoppingCart', 'IndexController@shoppingCart')->name('shopping.cart');

    Route::get('Reg', 'IndexController@Reg')->name('reg');
    Route::post('userRegister', 'UserController@userRegister')->name('user.register')->middleware('throttle:5,1');
    Route::post('fastRegister', 'Auth\RegisterController@fastRegister')->name('fastRegister')->middleware('throttle:5,1');

    Route::post('commentStoreSec', 'CommentController@storesec')->name('comment.store.sec');
    Route::get('commentEdit/{comment}', 'CommentController@commentEdit')->name('commentEdit');
    Route::match(['GET', 'POST'], 'commentAnswer/{comment}', 'CommentController@commentAnswer')->name('commentAnswer');

    Route::post('faq', 'FaqController@storesec')->name('faq.store.sec');
    Route::get('faqEdit/{faq}', 'FaqController@faqEdit')->name('faqEdit');
    Route::match(['GET', 'POST'], 'faqAnswer/{faq}', 'FaqController@faqAnswer')->name('faqAnswer');

    Route::get('reportListOfAllProductsHasDiscount', 'DiscountForAllController@reportListOfAllProductsHasDiscount')->name('reportListOfAllProductsHasDiscount');
    Route::get('reportListOfAllProductsHasDiscountCode', 'DiscountForAllController@reportListOfAllProductsHasDiscountCode')->name('reportListOfAllProductsHasDiscountCode');
    Route::get('reportListOfAllUsersHasDiscountCode', 'DiscountForAllController@reportListOfAllUsersHasDiscountCode')->name('reportListOfAllUsersHasDiscountCode');
    Route::get('reportListOfAllUsersBuyWithDiscountCode', 'DiscountForAllController@reportListOfAllUsersBuyWithDiscountCode')->name('reportListOfAllUsersBuyWithDiscountCode');
    Route::get('reportListOfAllProductsHasDiscount', 'DiscountForAllController@reportListOfAllProductsHasDiscount')->name('reportListOfAllProductsHasDiscount');

    Route::get('managerReport', 'AdminController@managerReport')->name('manager.report');

    Route::get('teacherUploadFileReport', 'AdminController@teacherUploadFileReport')->name('teacherUploadFileReport');

    Route::match(['GET', 'POST', 'DELETE'], 'profile/teacherProductPost/{product}/{id?}', 'ProfileController@createProductPostByTeacher')->name('createProductPostByTeacher');
    Route::match(['GET', 'POST'], 'profile/teacherProductFiles/{product}/{id?}', 'ProfileController@ProductFilesByTeacher')->name('ProductFilesByTeacher');
    Route::match(['GET', 'POST'], 'profile/teacherProductNotes/{product}/{id?}', 'ProfileController@ProductNotesByTeacher')->name('ProductNotesByTeacher');

    Route::post('productRating', 'IndexController@productRating')->name('productRating');

    Route::post('giveMobileNumber', 'IndexController@giveMobileNumber')->name('giveMobileNumber');

    Route::patch('editUserAddress', 'IndexController@editUserAddress')->name('editUserAddress');

    Route::get('post/{post}', 'IndexController@indexPost')->name('indexPost');

    //Gate:
    Route::get('functionGate/{factor}', 'GateController@functionGate')->name('functionGate');
    Route::get('callbackFunctionGate', 'GateController@callbackFunctionGate')->name('callbackFunctionGate');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('products', 'ProductController');
    Route::resource('users', 'UserController');
    Route::resource('factors', 'FactorController');
    Route::resource('categories', 'CategoryController');
    Route::resource('tags', 'TagController');
    Route::resource('comments', 'CommentController');
    Route::resource('posts', 'PostController');
    Route::resource('productPosts', 'ProductPostController');
    Route::resource('tickets', 'TicketController');
    Route::resource('messages', 'MessageController');
    Route::resource('discounts', 'DiscountController');
    Route::resource('settings', 'SettingController');
    Route::resource('teachingRequests', 'TeachingRequestController');
    Route::resource('teachingRequestComments', 'TeachingRequestCommentController');
    Route::resource('userDocuments', 'UserDocumentController');
    Route::resource('ticketComments', 'TicketCommentController');
    Route::resource('productFiles', 'ProductFileController');
    Route::resource('productNotes', 'ProductNoteController');
    Route::resource('productTypes', 'ProductTypeController');
    Route::resource('faqs', 'FaqController');
    Route::resource('indexNotifications', 'IndexNotificationController');
    Route::resource('indexVipProducts', 'IndexVipProductController');
    Route::resource('mobiles', 'MobileController');


    Route::group(['middleware' => 'elf'], function () {
        Route::get('elf/tinymce4', function () {
            $dir = '/packages/barryvdh/elfinder';
            $locale = 'fa';

            return view('vendor.elfinder.tinymce4', compact('dir', 'locale'));
        })->name('elfinder.tinymce4');
    });

    Route::get('downloadTeachingRequestFiles/{file}', function ($file) {
        $file = str_replace(':', '/', $file);

        return Storage::download('/public/teachingRequest/' . $file);
    })->name('downloadTeachingRequestFiles');

    Route::get('downloadTicketFiles/{file}', function ($file) {
        $file = str_replace(':', '/', $file);

        return Storage::download('/public/tickets/' . $file);
    })->name('downloadTicketFiles');


    Route::get('download/{file}', function ($file) {
        $file = str_replace(':', '/', $file);

        return Storage::download('/public/productFiles/' . $file);
    })->name('downloadFiles');

    ////last address

app/Http/Controllers/ProductTypeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProductTypeDataTable;
use App\Http\Requests\CreateProductTypeRequest;
use App\Http\Requests\UpdateProductTypeRequest;
use App\Repositories\ProductTypeRepository;
use Flash;
use Response;

class ProductTypeController extends AppBaseController
{
    /** @var  ProductTypeRepository */
    private $productTypeRepository;

    public function __construct(ProductTypeRepository $productTypeRepo)
    {
        $this->productTypeRepository = $productTypeRepo;
    }

    /**
     * Display a listing of the ProductType.
     *
     * @param ProductTypeDataTable $productTypeDataTable
     * @return Response
     */
    public function index(ProductTypeDataTable $productTypeDataTable)
    {
        $this->authorize('is-employee');

        return $productTypeDataTable->render('product_types.index');
    }

    /**
     * Show the form for creating a new ProductType.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('is-employee');

        return view('product_types.create');
    }

    /**
     * Store a newly created ProductType in storage.
     *
     * @param CreateProductTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateProductTypeRequest $request)
    {
        $this->authorize('is-employee');

        $input = $request->all();

        $productType = $this->productTypeRepository->create($input);

        Flash::success('نوع دوره با موفقیت ذخیره شد.');

        return redirect(route('productTypes.index'));
    }

    /**
     * Display the specified ProductType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $this->authorize('is-employee');

        $productType = $this->productTypeRepository->findWithoutFail($id);

        if (empty($productType)) {
            Flash::error('نوع دوره پیدا نشد.');

            return redirect(route('productTypes.index'));
        }

        return view('product_types.show')->with('productType', $productType);
    }

    /**
     * Show the form for editing the specified ProductType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $this->authorize('is-employee');

        $productType = $this->productTypeRepository->findWithoutFail($id);

        if (empty($productType)) {
            Flash::error('نوع دوره پیدا نشد.');

            return redirect(route('productTypes.index'));
        }

        return view('product_types.edit')->with('productType', $productType);
    }

    /**
     * Update the specified ProductType in storage.
     *
     * @param  int              $id
     * @param UpdateProductTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductTypeRequest $request)
    {
        $this->authorize('is-employee');

        $productType = $this->productTypeRepository->findWithoutFail($id);

        if (empty($productType)) {
            Flash::error('نوع دوره پیدا نشد.');

            return redirect(route('productTypes.index'));
        }

        $productType = $this->productTypeRepository->update($request->all(), $id);

        Flash::success('نوع دوره با موفقیت بروزرسانی شد.');

        return redirect(route('productTypes.index'));
    }

    /**
     * Remove the specified ProductType from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $this->authorize('is-employee');

        $productType = $this->productTypeRepository->findWithoutFail($id);

        if (empty($productType)) {
            Flash::error('نوع دوره پیدا نشد.');

            return redirect(route('productTypes.index'));
        }

        $this->productTypeRepository->delete($id);

        Flash::success('نوع دوره با موفقیت پاک شد.');

        return redirect(route('productTypes.index'));
    }
}

resources/views/product_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            ساختن نوع دوره ها
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'productTypes.store']) !!}

                        @include('product_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_types/datatables_actions.blade.php
{!! Form::open(['route' => ['productTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('productTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('productTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('آیا اطمینان دارید؟')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/product_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            نوع دوره ها
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($productType, ['route' => ['productTypes.update', $productType->id], 'method' => 'patch']) !!}

                        @include('product_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/product_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'نام:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Fa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name_fa', 'نام نمایشی(فارسی):') !!}
    {!! Form::text('name_fa', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('ذخیره', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('productTypes.index') !!}" class="btn btn-default">لغو</a>
</div>

resources/views/product_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">نوع دوره ها</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('productTypes.create') !!}">افزودن جدید</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('product_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/product_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            نوع دوره
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding:0 20px">
                    @include('product_types.show_fields')
                    <a href="{!! route('productTypes.index') !!}" class="btn btn-default">بازگشت</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product_types/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'شناسه:') !!}
    <p>{!! $productType->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'نام:') !!}
    <p>{!! $productType->name !!}</p>
</div>

<!-- Name Fa Field -->
<div class="form-group">
    {!! Form::label('name_fa', 'نام فارسی:') !!}
    <p>{!! $productType->name_fa !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'تاریخ ساخت:') !!}
    <p>{!! $productType->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'تاریخ بروز رسانی:') !!}
    <p>{!! $productType->updated_at !!}</p>
</div>

resources/views/product_types/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection