routes/web.php
    Route::get('category/{category?}', 'IndexController@category')->name('category');
    Route::post('category/' . 1 . '/sort_keyboard', 'AdminController@sortCategory');
    Route::match(['DELETE', 'PUT', 'GET', 'POST'], 'eshantion/{id?}', 'AdminController@eshantion')->name('eshantion');
    Route::get('visitorlog', 'AdminController@visitorlog')->name('visitorlog');

    //Route::get('profile/show/', 'IndexController@profile')->name('user.profile');//unused

    //Route::post('/profile/payFactor', 'IndexController@payFactor')->name('pay.factor');//unused

    //Route::get('/pmBox', 'IndexController@pmBox')->name('pmBox.get');//unused

    Route::post('/discountPost', 'IndexController@discountPost')->name('discount.post');

    Route::any('discountFestival', 'DiscountForAllController@discountFestival')->name('discountFestival');

    Route::any('discountForProducts', 'DiscountForAllController@discountForProducts')->name('discountForProducts');
    Route::any('discountForCategoryOfProducts', 'DiscountForAllController@discountForCategoryOfProducts')->name('discountForCategoryOfProducts');
    Route::any('discountForUsers', 'DiscountForAllController@discountForUsers')->name('discountForUsers');

    Route::any('discountCodeForProducts', 'DiscountForAllController@discountCodeForProducts')->name('discountCodeForProducts');
    Route::any('discountCodeForCategoryOfProducts', 'DiscountForAllController@discountCodeForCategoryOfProducts')->name('discountCodeForCategoryOfProducts');
    Route::any('discountCodeForUsers', 'DiscountForAllController@discountCodeForUsers')->name('discountCodeForUsers');

    Route::any('discountForPrice', 'DiscountForAllController@discountForPrice')->name('discountForPrice');

    //Route::get('/userFactors', 'ProfileController@userFactors')->name('userFactors');//unused
    //Route::get('/profile', 'ProfileController@profileGet')->name('profile.get');//unused
    Route::get('/profile/edit', 'ProfileController@profileEdit')->name('profile.edit');
    Route::post('/profile/post', 'ProfileController@profilePost')->name('profile.post');
    Route::post('profile/financialIncreaseBalance', 'ProfileController@increaseBalancePost')->name('increase.balance.post');
    Route::get('profile/financialIncreaseBalance', 'ProfileController@increaseBalanceGet')->name('increase.balance.get');
    Route::get('profile/financialDepartment', 'ProfileController@financialDepartment')->name('financialDepartment');
    Route::match(['GET', 'POST'], 'profile/financialWithdraw', 'ProfileController@financialWithdraw')->name('financialWithdraw');

    Route::match(['GET', 'POST'], 'profile/ticketCreate', 'ProfileController@ticketCreate')->name('ticketCreate');
    Route::match(['GET', 'POST'], 'profile/ticketComments/{id}', 'ProfileController@ticketComments')->name('ticketComments');
    Route::get('profile/ticketIndex', 'ProfileController@ticketIndex')->name('ticketIndex');//unused
    Route::get('profile/userCourses', 'ProfileController@userCourses')->name('userCourses');
    Route::get('profile/courseStudent', 'ProfileController@courseStudent')->name('courseStudent');

    Route::get('profile/teachingIndex', 'ProfileController@teachingIndex')->name('teachingIndex');
    Route::match(['GET', 'POST'], 'profile/teachingRequestCreate', 'ProfileController@teachingRequestCreate')->name('teachingRequestCreate');
    Route::match(['GET', 'POST'], 'profile/teachingRequestComments/{id}', 'ProfileController@teachingRequestComments')->name('teachingRequestComments');
    Route::get('profile/teacherEditProducts/{product}', 'ProductController@teacherEditProducts')->name('teacherEditProducts');
    Route::post('profile/teacherUpdateProducts/{product}', 'ProductController@teacherUpdateProducts')->name('teacherUpdateProducts');

    Route::get('post/{post}', 'IndexController@showAPost')->name('show.post');
    //Route::get('productPost/{productPost}', 'IndexController@showProductPost')->name('show.product.post');//unused

    Route::match(['GET', 'POST'], 'adminFinancialWithdraw/{balanceHistory?}', 'AdminController@adminFinancialWithdraw')->name('adminFinancialWithdraw');
    Route::get('upload', 'UploadController@uploadGet')->name('upload.get');
    Route::post('upload', 'UploadController@uploadPost')->name('upload.post');

    Route::post('addToBasket/{id}', 'IndexController@addToBasket')->name('add.to.basket');
    Route::post('removeFromBasket/{id}', 'IndexController@removeFromBasket')->name('remove.from.basket');
    Route::put('signUpNoPrice/{id}', 'IndexController@signUpNoPrice')->name('signUpNoPrice');

    Route::get('checkOut', 'IndexController@checkOut')->name('check.out');

    Route::get('shoppingCart', 'IndexController@shoppingCart')->name('shopping.cart');

    Route::get('Reg', 'IndexController@Reg')->name('reg');
    Route::post('userRegister', 'UserController@userRegister')->name('user.register')->middleware('throttle:5,1');
    Route::post('fastRegister', 'Auth\RegisterController@fastRegister')->name('fastRegister')->middleware('throttle:5,1');

    Route::post('commentStoreSec', 'CommentController@storesec')->name('comment.store.sec');
    Route::get('commentEdit/{comment}', 'CommentController@commentEdit')->name('commentEdit');
    Route::match(['GET', 'POST'], 'commentAnswer/{comment}', 'CommentController@commentAnswer')->name('commentAnswer');

    Route::post('faq', 'FaqController@storesec')->name('faq.store.sec');
    Route::get('faqEdit/{faq}', 'FaqController@faqEdit')->name('faqEdit');
    Route::match(['GET', 'POST'], 'faqAnswer/{faq}', 'FaqController@faqAnswer')->name('faqAnswer');

    Route::get('reportListOfAllProductsHasDiscount', 'DiscountForAllController@reportListOfAllProductsHasDiscount')->name('reportListOfAllProductsHasDiscount');
    Route::get('reportListOfAllProductsHasDiscountCode', 'DiscountForAllController@reportListOfAllProductsHasDiscountCode')->name('reportListOfAllProductsHasDiscountCode');
    Route::get('reportListOfAllUsersHasDiscountCode', 'DiscountForAllController@reportListOfAllUsersHasDiscountCode')->name('reportListOfAllUsersHasDiscountCode');
    Route::get('reportListOfAllUsersBuyWithDiscountCode', 'DiscountForAllController@reportListOfAllUsersBuyWithDiscountCode')->name('reportListOfAllUsersBuyWithDiscountCode');
    Route::get('reportListOfAllProductsHasDiscount', 'DiscountForAllController@reportListOfAllProductsHasDiscount')->name('reportListOfAllProductsHasDiscount');

    Route::get('managerReport', 'AdminController@managerReport')->name('manager.report');

    Route::get('teacherUploadFileReport', 'AdminController@teacherUploadFileReport')->name('teacherUploadFileReport');

    Route::match(['GET', 'POST', 'DELETE'], 'profile/teacherProductPost/{product}/{id?}', 'ProfileController@createProductPostByTeacher')->name('createProductPostByTeacher');
    Route::match(['GET', 'POST'], 'profile/teacherProductFiles/{product}/{id?}', 'ProfileController@ProductFilesByTeacher')->name('ProductFilesByTeacher');
    Route::match(['GET', 'POST'], 'profile/teacherProductNotes/{product}/{id?}', 'ProfileController@ProductNotesByTeacher')->name('ProductNotesByTeacher');

    Route::post('productRating', 'IndexController@productRating')->name('productRating');

    Route::post('giveMobileNumber', 'IndexController@giveMobileNumber')->name('giveMobileNumber');

    Route::patch('editUserAddress', 'IndexController@editUserAddress')->name('editUserAddress');

    Route::get('post/{post}', 'IndexController@indexPost')->name('indexPost');

    //Gate:
    Route::get('functionGate/{factor}', 'GateController@functionGate')->name('functionGate');
    Route::get('callbackFunctionGate', 'GateController@callbackFunctionGate')->name('callbackFunctionGate');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('products', 'ProductController');
    Route::resource('users', 'UserController');
    Route::resource('factors', 'FactorController');
    Route::resource('categories', 'CategoryController');
    Route::resource('tags', 'TagController');
    Route::resource('comments', 'CommentController');
    Route::resource('posts', 'PostController');
    Route::resource('productPosts', 'ProductPostController');
    Route::resource('tickets', 'TicketController');
    Route::resource('messages', 'MessageController');
    Route::resource('discounts', 'DiscountController');
    Route::resource('settings', 'SettingController');
    Route::resource('teachingRequests', 'TeachingRequestController');
    Route::resource('teachingRequestComments', 'TeachingRequestCommentController');
    Route::resource('userDocuments', 'UserDocumentController');
    Route::resource('ticketComments', 'TicketCommentController');
    Route::resource('productFiles', 'ProductFileController');
    Route::resource('productNotes', 'ProductNoteController');
    Route::resource('productTypes', 'ProductTypeController');
    Route::resource('faqs', 'FaqController');
    Route::resource('indexNotifications', 'IndexNotificationController');
    Route::resource('indexVipProducts', 'IndexVipProductController');
    Route::resource('mobiles', 'MobileController');


    Route::group(['middleware' => 'elf'], function () {
        Route::get('elf/tinymce4', function () {
            $dir = '/packages/barryvdh/elfinder';
            $locale = 'fa';

            return view('vendor.elfinder.tinymce4', compact('dir', 'locale'));
        })->name('elfinder.tinymce4');
    });

    Route::get('downloadTeachingRequestFiles/{file}', function ($file) {
        $file = str_replace(':', '/', $file);

        return Storage::download('/public/teachingRequest/' . $file);
    })->name('downloadTeachingRequestFiles');

    Route::get('downloadTicketFiles/{file}', function ($file) {
        $file = str_replace(':', '/', $file);

        return Storage::download('/public/tickets/' . $file);
    })->name('downloadTicketFiles');


    Route::get('download/{file}', function ($file) {

app/Models/TeachingRequestComment.php
<?php

namespace App\Models;

use App\User;
use Eloquent as Model;

/**
 * Class TeachingRequestComment
 * @package App\Models
 * @version February 13, 2018, 10:59 am +0330
 *
 * @property integer teaching_request_id
 * @property integer user_id
 * @property integer parent_id
 * @property string text
 */
class TeachingRequestComment extends Model
{

    public $table = 'teaching_request_comments';
    


    public $fillable = [
        'teaching_request_id',
        'user_id',
        'parent_id',
        'text'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'teaching_request_id' => 'integer',
        'user_id' => 'integer',
        'parent_id' => 'integer',
        'text' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TeachingRequestCommentController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TeachingRequestCommentDataTable;
use App\Http\Requests\CreateTeachingRequestCommentRequest;
use App\Http\Requests\UpdateTeachingRequestCommentRequest;
use App\Repositories\TeachingRequestCommentRepository;
use Flash;
use Response;

class TeachingRequestCommentController extends AppBaseController
{
    /** @var  TeachingRequestCommentRepository */
    private $teachingRequestCommentRepository;

    public function __construct(TeachingRequestCommentRepository $teachingRequestCommentRepo)
    {
        $this->teachingRequestCommentRepository = $teachingRequestCommentRepo;
    }

    /**
     * Display a listing of the TeachingRequestComment.
     *
     * @param TeachingRequestCommentDataTable $teachingRequestCommentDataTable
     * @return Response
     */
    public function index(TeachingRequestCommentDataTable $teachingRequestCommentDataTable)
    {
        $this->authorize('is-employee');

        return $teachingRequestCommentDataTable->render('teaching_request_comments.index');
    }

    /**
     * Show the form for creating a new TeachingRequestComment.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('is-employee');

        return view('teaching_request_comments.create');
    }

    /**
     * Store a newly created TeachingRequestComment in storage.
     *
     * @param CreateTeachingRequestCommentRequest $request
     *
     * @return Response
     */
    public function store(CreateTeachingRequestCommentRequest $request)
    {
        $this->authorize('is-employee');

        $input = $request->all();

        $teachingRequestComment = $this->teachingRequestCommentRepository->create($input);

        Flash::success('Teaching Request Comment saved successfully.');

        return redirect(route('teachingRequestComments.index'));
    }

    /**
     * Display the specified TeachingRequestComment.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $this->authorize('is-employee');

        $teachingRequestComment = $this->teachingRequestCommentRepository->findWithoutFail($id);

        if (empty($teachingRequestComment)) {
            Flash::error('Teaching Request Comment not found');

            return redirect(route('teachingRequestComments.index'));
        }

        return view('teaching_request_comments.show')->with('teachingRequestComment', $teachingRequestComment);
    }

    /**
     * Show the form for editing the specified TeachingRequestComment.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $this->authorize('is-employee');

        $teachingRequestComment = $this->teachingRequestCommentRepository->findWithoutFail($id);

        if (empty($teachingRequestComment)) {
            Flash::error('Teaching Request Comment not found');

            return redirect(route('teachingRequestComments.index'));
        }

        return view('teaching_request_comments.edit')->with('teachingRequestComment', $teachingRequestComment);
    }

    /**
     * Update the specified TeachingRequestComment in storage.
     *
     * @param  int              $id
     * @param UpdateTeachingRequestCommentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTeachingRequestCommentRequest $request)
    {
        $this->authorize('is-employee');

        $teachingRequestComment = $this->teachingRequestCommentRepository->findWithoutFail($id);

        if (empty($teachingRequestComment)) {
            Flash::error('Teaching Request Comment not found');

            return redirect(route('teachingRequestComments.index'));
        }

        $teachingRequestComment = $this->teachingRequestCommentRepository->update($request->all(), $id);

        Flash::success('Teaching Request Comment updated successfully.');

        return redirect(route('teachingRequestComments.index'));
    }

    /**
     * Remove the specified TeachingRequestComment from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $this->authorize('is-employee');

        $teachingRequestComment = $this->teachingRequestCommentRepository->findWithoutFail($id);

        if (empty($teachingRequestComment)) {
            Flash::error('Teaching Request Comment not found');

            return redirect(route('teachingRequestComments.index'));
        }

        $this->teachingRequestCommentRepository->delete($id);

        Flash::success('Teaching Request Comment deleted successfully.');

        return redirect(route('teachingRequestComments.index'));
    }
}

resources/views/teaching_request_comments/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Teaching Request Comment
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'teachingRequestComments.store']) !!}

                        @include('teaching_request_comments.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/teaching_request_comments/datatables_actions.blade.php
{!! Form::open(['route' => ['teachingRequestComments.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('teachingRequestComments.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('teachingRequestComments.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/teaching_request_comments/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Teaching Request Comment
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($teachingRequestComment, ['route' => ['teachingRequestComments.update', $teachingRequestComment->id], 'method' => 'patch']) !!}

                        @include('teaching_request_comments.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/teaching_request_comments/fields.blade.php
<!-- Teaching Request Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('teaching_request_id', 'Teaching Request Id:') !!}
    {!! Form::text('teaching_request_id', null, ['class' => 'form-control']) !!}
</div>

<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::text('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Parent Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('parent_id', 'Parent Id:') !!}
    {!! Form::text('parent_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Text Field -->
<div class="form-group col-sm-6">
    {!! Form::label('text', 'Text:') !!}
    {!! Form::text('text', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('teachingRequestComments.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/teaching_request_comments/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Teaching Request Comments</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('teachingRequestComments.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('teaching_request_comments.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/teaching_request_comments/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Teaching Request Comment
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('teaching_request_comments.show_fields')
                    <a href="{!! route('teachingRequestComments.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/teaching_request_comments/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $teachingRequestComment->id !!}</p>
</div>

<!-- Teaching Request Id Field -->
<div class="form-group">
    {!! Form::label('teaching_request_id', 'Teaching Request Id:') !!}
    <p>{!! $teachingRequestComment->teaching_request_id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $teachingRequestComment->user_id !!}</p>
</div>

<!-- Parent Id Field -->
<div class="form-group">
    {!! Form::label('parent_id', 'Parent Id:') !!}
    <p>{!! $teachingRequestComment->parent_id !!}</p>
</div>

<!-- Text Field -->
<div class="form-group">
    {!! Form::label('text', 'Text:') !!}
    <p>{!! $teachingRequestComment->text !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $teachingRequestComment->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $teachingRequestComment->updated_at !!}</p>
</div>

resources/views/teaching_request_comments/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection