routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'visitorlog'], function () {

    Route::get('/', 'IndexController@index')->name('index.index');

    Route::get('category/{category?}', 'IndexController@category')->name('category');
    Route::post('category/' . 1 . '/sort_keyboard', 'AdminController@sortCategory');
    Route::match(['DELETE', 'PUT', 'GET', 'POST'], 'eshantion/{id?}', 'AdminController@eshantion')->name('eshantion');
    Route::get('visitorlog', 'AdminController@visitorlog')->name('visitorlog');

    //Route::get('profile/show/', 'IndexController@profile')->name('user.profile');//unused

    //Route::post('/profile/payFactor', 'IndexController@payFactor')->name('pay.factor');//unused

    //Route::get('/pmBox', 'IndexController@pmBox')->name('pmBox.get');//unused

    Route::post('/discountPost', 'IndexController@discountPost')->name('discount.post');

    Route::any('discountFestival', 'DiscountForAllController@discountFestival')->name('discountFestival');

    Route::any('discountForProducts', 'DiscountForAllController@discountForProducts')->name('discountForProducts');
    Route::any('discountForCategoryOfProducts', 'DiscountForAllController@discountForCategoryOfProducts')->name('discountForCategoryOfProducts');
    Route::any('discountForUsers', 'DiscountForAllController@discountForUsers')->name('discountForUsers');

    Route::any('discountCodeForProducts', 'DiscountForAllController@discountCodeForProducts')->name('discountCodeForProducts');
    Route::any('discountCodeForCategoryOfProducts', 'DiscountForAllController@discountCodeForCategoryOfProducts')->name('discountCodeForCategoryOfProducts');
    Route::any('discountCodeForUsers', 'DiscountForAllController@discountCodeForUsers')->name('discountCodeForUsers');

    Route::any('discountForPrice', 'DiscountForAllController@discountForPrice')->name('discountForPrice');

    //Route::get('/userFactors', 'ProfileController@userFactors')->name('userFactors');//unused
    //Route::get('/profile', 'ProfileController@profileGet')->name('profile.get');//unused
    Route::get('/profile/edit', 'ProfileController@profileEdit')->name('profile.edit');
    Route::post('/profile/post', 'ProfileController@profilePost')->name('profile.post');
    Route::post('profile/financialIncreaseBalance', 'ProfileController@increaseBalancePost')->name('increase.balance.post');
    Route::get('profile/financialIncreaseBalance', 'ProfileController@increaseBalanceGet')->name('increase.balance.get');
    Route::get('profile/financialDepartment', 'ProfileController@financialDepartment')->name('financialDepartment');
    Route::match(['GET', 'POST'], 'profile/financialWithdraw', 'ProfileController@financialWithdraw')->name('financialWithdraw');

    Route::match(['GET', 'POST'], 'profile/ticketCreate', 'ProfileController@ticketCreate')->name('ticketCreate');
    Route::match(['GET', 'POST'], 'profile/ticketComments/{id}', 'ProfileController@ticketComments')->name('ticketComments');
    Route::get('profile/ticketIndex', 'ProfileController@ticketIndex')->name('ticketIndex');//unused
    Route::get('profile/userCourses', 'ProfileController@userCourses')->name('userCourses');
    Route::get('profile/courseStudent', 'ProfileController@courseStudent')->name('courseStudent');

    Route::get('profile/teachingIndex', 'ProfileController@teachingIndex')->name('teachingIndex');
    Route::match(['GET', 'POST'], 'profile/teachingRequestCreate', 'ProfileController@teachingRequestCreate')->name('teachingRequestCreate');
    Route::match(['GET', 'POST'], 'profile/teachingRequestComments/{id}', 'ProfileController@teachingRequestComments')->name('teachingRequestComments');
    Route::get('profile/teacherEditProducts/{product}', 'ProductController@teacherEditProducts')->name('teacherEditProducts');
    Route::post('profile/teacherUpdateProducts/{product}', 'ProductController@teacherUpdateProducts')->name('teacherUpdateProducts');

    Route::get('post/{post}', 'IndexController@showAPost')->name('show.post');
    //Route::get('productPost/{productPost}', 'IndexController@showProductPost')->name('show.product.post');//unused

    Route::match(['GET', 'POST'], 'adminFinancialWithdraw/{balanceHistory?}', 'AdminController@adminFinancialWithdraw')->name('adminFinancialWithdraw');
    Route::get('upload', 'UploadController@uploadGet')->name('upload.get');
    Route::post('upload', 'UploadController@uploadPost')->name('upload.post');

    Route::post('addToBasket/{id}', 'IndexController@addToBasket')->name('add.to.basket');
    Route::post('removeFromBasket/{id}', 'IndexController@removeFromBasket')->name('remove.from.basket');
    Route::put('signUpNoPrice/{id}', 'IndexController@signUpNoPrice')->name('signUpNoPrice');

    Route::get('checkOut', 'IndexController@checkOut')->name('check.out');

    Route::get('shoppingCart', 'IndexController@shoppingCart')->name('shopping.cart');

    Route::get('Reg', 'IndexController@Reg')->name('reg');
    Route::post('userRegister', 'UserController@userRegister')->name('user.register')->middleware('throttle:5,1');
    Route::post('fastRegister', 'Auth\RegisterController@fastRegister')->name('fastRegister')->middleware('throttle:5,1');

    Route::post('commentStoreSec', 'CommentController@storesec')->name('comment.store.sec');
    Route::get('commentEdit/{comment}', 'CommentController@commentEdit')->name('commentEdit');
    Route::match(['GET', 'POST'], 'commentAnswer/{comment}', 'CommentController@commentAnswer')->name('commentAnswer');

    Route::post('faq', 'FaqController@storesec')->name('faq.store.sec');
    Route::get('faqEdit/{faq}', 'FaqController@faqEdit')->name('faqEdit');
    Route::match(['GET', 'POST'], 'faqAnswer/{faq}', 'FaqController@faqAnswer')->name('faqAnswer');

    Route::get('reportListOfAllProductsHasDiscount', 'DiscountForAllController@reportListOfAllProductsHasDiscount')->name('reportListOfAllProductsHasDiscount');
    Route::get('reportListOfAllProductsHasDiscountCode', 'DiscountForAllController@reportListOfAllProductsHasDiscountCode')->name('reportListOfAllProductsHasDiscountCode');
    Route::get('reportListOfAllUsersHasDiscountCode', 'DiscountForAllController@reportListOfAllUsersHasDiscountCode')->name('reportListOfAllUsersHasDiscountCode');
    Route::get('reportListOfAllUsersBuyWithDiscountCode', 'DiscountForAllController@reportListOfAllUsersBuyWithDiscountCode')->name('reportListOfAllUsersBuyWithDiscountCode');
    Route::get('reportListOfAllProductsHasDiscount', 'DiscountForAllController@reportListOfAllProductsHasDiscount')->name('reportListOfAllProductsHasDiscount');

    Route::get('managerReport', 'AdminController@managerReport')->name('manager.report');

    Route::get('teacherUploadFileReport', 'AdminController@teacherUploadFileReport')->name('teacherUploadFileReport');

    Route::match(['GET', 'POST', 'DELETE'], 'profile/teacherProductPost/{product}/{id?}', 'ProfileController@createProductPostByTeacher')->name('createProductPostByTeacher');
    Route::match(['GET', 'POST'], 'profile/teacherProductFiles/{product}/{id?}', 'ProfileController@ProductFilesByTeacher')->name('ProductFilesByTeacher');
    Route::match(['GET', 'POST'], 'profile/teacherProductNotes/{product}/{id?}', 'ProfileController@ProductNotesByTeacher')->name('ProductNotesByTeacher');

    Route::post('productRating', 'IndexController@productRating')->name('productRating');

    Route::post('giveMobileNumber', 'IndexController@giveMobileNumber')->name('giveMobileNumber');

    Route::patch('editUserAddress', 'IndexController@editUserAddress')->name('editUserAddress');

    Route::get('post/{post}', 'IndexController@indexPost')->name('indexPost');

    //Gate:
    Route::get('functionGate/{factor}', 'GateController@functionGate')->name('functionGate');
    Route::get('callbackFunctionGate', 'GateController@callbackFunctionGate')->name('callbackFunctionGate');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('products', 'ProductController');
    Route::resource('users', 'UserController');
    Route::resource('factors', 'FactorController');
    Route::resource('categories', 'CategoryController');
    Route::resource('tags', 'TagController');
    Route::resource('comments', 'CommentController');
    Route::resource('posts', 'PostController');
    Route::resource('productPosts', 'ProductPostController');
    Route::resource('tickets', 'TicketController');
    Route::resource('messages', 'MessageController');
    Route::resource('discounts', 'DiscountController');
    Route::resource('settings', 'SettingController');
    Route::resource('teachingRequests', 'TeachingRequestController');
    Route::resource('teachingRequestComments', 'TeachingRequestCommentController');
    Route::resource('userDocuments', 'UserDocumentController');
    Route::resource('ticketComments', 'TicketCommentController');
    Route::resource('productFiles', 'ProductFileController');
    Route::resource('productNotes', 'ProductNoteController');
    Route::resource('productTypes', 'ProductTypeController');
    Route::resource('faqs', 'FaqController');
    Route::resource('indexNotifications', 'IndexNotificationController');
    Route::resource('indexVipProducts', 'IndexVipProductController');
    Route::resource('mobiles', 'MobileController');


    Route::group(['middleware' => 'elf'], function () {
        Route::get('elf/tinymce4', function () {
            $dir = '/packages/barryvdh/elfinder';
            $locale = 'fa';

            return view('vendor.elfinder.tinymce4', compact('dir', 'locale'));
        })->name('elfinder.tinymce4');
    });

app/Models/Product.php
<?php

namespace App\Models;

use App\User;
use Eloquent as Model;

/**
 * Class Product
 * @package App\Models
 * @version January 15, 2018, 6:07 pm UTC
 *
 * @property string title
 * @property string description
 * @property string download_link
 * @property integer count
 * @property integer price
 * @property integer discount
 * @property string image_main
 * @property string image_two
 * @property string image_three
 * @property string image_four
 * @property string image_five
 */
class Product extends Model
{

    public $table = 'products';

    public $fillable = [
        'title',
        'description_mini',
        'description',
        'description_full',
        'specification',
        'download_link',
        'price',
        'real_price',
        'discount',
        'total_count',
        'sold_count',
        'brand',
        'duration',
        'vote',
        'total_voters',
        'is_active',
        'image_main',
        'user_earn_vote',
        'can_get_license',
        'can_sign_up',
        'rating_movie',
        'rating_voice',
        'rating_complete',
        'rating_teacher',
        'rating_support',
        'rating_rezayat',
        'start_at',
        'end_at',
        'status',
        'product_type_id',
        'user_id',
        'category_id',
        'special_duration',
        'special_city',
        'special_teacher_name',
        'special_address',
        'special_time',
        'special_tel',
        'total_visit',
        'thumbnail',


    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'title' => 'string',
        'description' => 'string',
        'download_link' => 'string',
        'count' => 'integer',
        'price' => 'integer',
        'discount' => 'integer',
        'image_main' => 'string',
        'image_two' => 'string',
        'image_three' => 'string',
        'image_four' => 'string',
        'image_five' => 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'required'
    ];

    public function getStatusStrItemsAttribute()
    {
        return [
            0 => 'به زودی برگزار خواهد شد.',
            1 => 'در حال برگزاری',
            2 => 'تکمیل شده',
        ];
    }

    public function getStatusStrAttribute()
    {
        switch ($this->status) {
            case 0:
                return 'به زودی برگزار خواهد شد.';
            case 1:
                return 'در حال برگزاری';
            case 2:
                return 'تکمیل شده';
        }
    }

    public function factors()
    {
        return $this->belongsToMany(Factor::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function faqs()
    {
        return $this->hasMany(Faq::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function discounts()
    {
        return $this->belongsToMany(Discount::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function productPosts()
    {
        return $this->hasMany(ProductPost::class);
    }

    public function students()
    {
        return $this->belongsToMany('App\User', 'lesson_student','lesson_id',  'student_id');
    }

    public function studentsDetail()
    {
        return $this->belongsToMany('App\User', 'lesson_student_detail','lesson_id',  'student_id');
    }

    public function productFiles()
    {
        return $this->hasMany(ProductFile::class);
    }

    public function productNotes()
    {
        return $this->hasMany(ProductNote::class);
    }

    public function UserRatings()//used
    {
        return $this->belongsToMany('App\User', 'product_rating_user', 'product_id', 'user_id');
    }

    public function productType()
    {
        return $this->belongsTo(ProductType::class);
    }

    public function eshantions()
    {
        return $this->belongsToMany(Product::class, 'eshantion_mahsulasli', 'mahsulasli_id', 'eshantion_id');
    }
}

app/Models/ProductType.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class ProductType
 * @package App\Models
 * @version March 2, 2018, 1:34 pm +0330
 *
 * @property string name
 * @property string name_fa
 */
class ProductType extends Model
{

    public $table = 'product_types';
    


    public $fillable = [
        'name',
        'name_fa'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'name_fa' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            ساختن دوره آموزشی
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'products.store', 'files' => true]) !!}

                        @include('products.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/datatables_actions.blade.php
{!! Form::open(['route' => ['products.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('products.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('products.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('آیا اطمینان دارید؟')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            ویرایش دوره آموزشی
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('products.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/products/fields.blade.php
<!-- فیلد دسته بندی: -->
<div class="form-group col-sm-6 {{ $errors->has('category_id') ? ' has-error' : '' }}">
    {!! Form::label('category_id', 'دسته بندی:') !!}
    {!! Form::select('category_id', $categories, (isset($product))?$product->categories:null, ['class' => 'form-control select2']) !!}
    @if ($errors->has('category_id'))
        <span class="help-block"><strong>{{ $errors->first('category_id') }}</strong></span>
    @endif
</div>

<!-- فیلد دسته بندی: -->
<div class="form-group col-sm-6 {{ $errors->has('user_id') ? ' has-error' : '' }}">
    {!! Form::label('user_id', 'انتخاب استاد:') !!}
    {!! Form::select('user_id', $users, (isset($product))?$product->user_id:null, ['class' => 'form-control select2']) !!}
    @if ($errors->has('user_id'))
        <span class="help-block"><strong>{{ $errors->first('user_id') }}</strong></span>
    @endif
</div>

{{--<!-- فیلد دسته بندی: -->--}}
{{--<div class="form-group col-sm-6 {{ $errors->has('tag_id[]') ? ' has-error' : '' }}">--}}
{{--{!! Form::label('tag_id[]', 'برچسب ها:') !!}--}}
{{--{!! Form::select('tag_id[]', $tags, (isset($product))?$product->tags:null, ['class' => 'form-control select2', 'multiple' => 'multiple']) !!}--}}
{{--@if ($errors->has('tag_id[]'))--}}
{{--<span class="help-block"><strong>{{ $errors->first('tag_id[]') }}</strong></span>--}}
{{--@endif--}}
{{--</div>--}}

<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', 'عنوان:') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description_mini', 'توضیحات مختصر:') !!}
    {!! Form::text('description_mini', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12">
    {!! Form::label('description', 'توضیحات:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'editorcm']) !!}
</div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', 'قیمت:') !!}
    {!! Form::text('price', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('discount', 'تخفیف:') !!}
    {!! Form::text('discount', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sold_count', 'تعداد فروش رفته:') !!}
    {!! Form::text('sold_count', null, ['class' => 'form-control']) !!}
</div>

<!-- Count Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_count', 'تعداد کل محصولات موجود در انبار:') !!}
    {!! Form::text('total_count', null, ['class' => 'form-control']) !!}
    <div class="help-block">اگر 0 باشد به تعداد نا محدود میتوان از این محصول فروخت اما اگر مثلا 20 باشد فقط 20 عدد از
        این محصول را مشتریان میتوانند بخرند
    </div>
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vote', 'امتیاز کل:') !!}
    {!! Form::text('vote', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating_movie', 'امتیاز فیلم:') !!}
    {!! Form::text('rating_movie', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating_voice', 'امتیاز صدا:') !!}
    {!! Form::text('rating_voice', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating_complete', 'امتیاز جامع بودن:') !!}
    {!! Form::text('rating_complete', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating_teacher', 'امتیاز استاد:') !!}
    {!! Form::text('rating_teacher', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating_support', 'امتیاز پشتیبانی:') !!}
    {!! Form::text('rating_support', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating_rezayat', 'امتیاز رضایت:') !!}
    {!! Form::text('rating_rezayat', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_voters', 'تعداد رای دهندگان:') !!}
    {!! Form::text('total_voters', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_visit', 'تعداد بازدیدکنندگان:') !!}
    {!! Form::text('total_visit', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_earn_score', 'امتیازی که از خرید محصول کاربران کسب میکنند:') !!}
    {!! Form::text('user_earn_score', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    <label for="">آیا محصول فعال است؟</label>
    <select name="is_active" id="" class="form-control">
        <option value="1" @if((isset($product)) && ($product->is_active == 1)) selected @endif>بله</option>
        <option value="0" @if((isset($product)) && ($product->is_active == 0)) selected @endif >خیر</option>
    </select>
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    <label for="">آیا امکان گرفتن گواهینامه وجود دارد؟</label>
    <select name="can_get_license" id="" class="form-control">
        <option value="1" @if((isset($product)) && ($product->can_get_license == 1)) selected @endif >بله</option>
        <option value="0" @if((isset($product)) && ($product->can_get_license == 0)) selected @endif>خیر</option>
    </select>
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    <label for="">آیا امکان ثبت نام برای کاربران وجود دارد؟</label>
    <select name="can_sign_up" id="" class="form-control">
        <option value="1" @if((isset($product)) && ($product->can_sign_up == 1)) selected @endif>بله</option>
        <option value="0" @if((isset($product)) && ($product->can_sign_up == 0)) selected @endif>خیر</option>
    </select>
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    <label for="">وضعیت؟</label>
    <select name="status" id="" class="form-control">
        <option value="0" @if((isset($product)) && ($product->status == 0)) selected @endif>به زودی برگزار خواهد شد
        </option>
        <option value="1" @if((isset($product)) && ($product->status == 1)) selected @endif>در حال برگزاری</option>
        <option value="2" @if((isset($product)) && ($product->status == 2)) selected @endif>تکمیل شده</option>
    </select>
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    <label for="">نوع محصول؟</label>
    <select name="product_type_id" id="" class="form-control">
        @foreach($productTypes as $productType)
            <option value="{{$productType->id}}"
                    @if((isset($product)) && ($product->product_type_id == $productType->id)) selected @endif>{{$productType->name_fa}}</option>
        @endforeach
    </select>
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start_at', 'زمان شروع:') !!}
    {!! Form::text('start_at', null, ['class' => 'form-control pDatePicker']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('end_at', 'زمان پایان:') !!}
    {!! Form::text('end_at', null, ['class' => 'form-control pDatePicker']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('special_duration', 'مدت دروس ویژه:') !!}
    {!! Form::text('special_duration', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('special_city', 'شهر دروس ویژه:') !!}
    {!! Form::text('special_city', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('special_address', 'متن آدرس دروس ویژه:') !!}
    {!! Form::text('special_address', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('special_time', 'متن زمان دروس ویژه:') !!}
    {!! Form::text('special_time', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('special_tel', 'متن تلفن دروس ویژه:') !!}
    {!! Form::text('special_tel', null, ['class' => 'form-control']) !!}
</div>

<!-- Discount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('special_teacher_name', 'اسم استاد دروس ویژه') !!}
    {!! Form::text('special_teacher_name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    <label for="image">عکس دوره</label>
    {!! Form::file('image')!!}
    {{--<input type="file" name="image">--}}

    @if(isset($product->image_main))
        <div>
            <label for="nowImage">عکس فعلی:</label>
            <img width="100%" src="{{showProductImage($product)}}" alt="" id="nowImage">
        </div>
    @endif
</div>

<div class="form-group col-sm-6">
    <button type="submit" class="btn btn-success">ذخیره</button>
</div>

@push('scripts')
    <script type="text/javascript" src="{{ asset('editor/full/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('editor/full/ckeditor/adapters/jquery.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('textarea#editorcm').ckeditor();
            $('html, body').animate({
                scrollTop: $("#myDiv").offset().top
            }, 2000);
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".pDatePicker").pDatepicker({
                altField: '#inlineExampleAlt',
                altFormat: 'LLLL',
                toolbox: {
                    calendarSwitch: {
                        enabled: true
                    }
                },
                navigator: {
                    scroll: {
                        enabled: false
                    }
                },
                maxDate: new persianDate().add('month', 12).valueOf(),
                minDate: new persianDate().subtract('month', 0).valueOf(),
                timePicker: {
                    enabled: true,
                    meridiem: {
                        enabled: true
                    }
                }
            });
        });
    </script>

@endpush

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">محصولات آموزشی</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('products.create') !!}">افزودن جدید</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('products.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            محصول آموزشی
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding:0 20px">
                    @include('products.show_fields')
                    <a href="{!! route('products.index') !!}" class="btn btn-default">بازگشت</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection